# Generated by Django 5.2.4 on 2026-03-10 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('production', '0001_initial'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklot',
            name='source_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_lots', to='production.productionbatch'),
        ),
        migrations.AddField(
            model_name='stocklot',
            name='source_purchase_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_lots', to='purchases.purchaseorderdetail'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='stock_lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.stocklot'),
        ),
    ]
