# Generated by Django 5.2.4 on 2026-03-19 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='current_unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='item',
            name='reorder_point',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stocklot',
            name='average_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='e.g. sqft per hide', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stocklot',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocklot',
            name='grade',
            field=models.CharField(choices=[('TR', 'TR'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('REJECT', 'Reject'), ('NA', 'N/A')], default='NA', max_length=10),
        ),
        migrations.AddField(
            model_name='stocklot',
            name='thickness',
            field=models.CharField(blank=True, help_text='e.g. 1.2 - 1.4 mm', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ItemPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('effective_date', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='MANUAL', max_length=50)),
                ('reference_document', models.CharField(blank=True, max_length=100, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='inventory.item')),
            ],
            options={
                'ordering': ['-effective_date'],
            },
        ),
        migrations.AddField(
            model_name='stocklot',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots', to='inventory.location'),
        ),
    ]
