# Generated by Django 5.2.12 on 2026-03-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_location_item_current_unit_price_item_reorder_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorydocument',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('VOIDED', 'Voided')], default='ACTIVE', max_length=10),
        ),
    ]
