# Generated by Django 5.2.4 on 2026-03-10 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100, unique=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('QA_HOLD', 'QA Hold'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sequence_order', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BatchChemicalUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('actual_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock_lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.stocklot')),
            ],
        ),
        migrations.CreateModel(
            name='BatchInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_weight', models.DecimalField(decimal_places=2, max_digits=12)),
                ('hide_count', models.PositiveIntegerField()),
                ('stock_lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.stocklot')),
            ],
        ),
        migrations.CreateModel(
            name='BatchOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('hide_count', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessChemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sequence_order', models.PositiveIntegerField()),
                ('ph_target', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('temperature_celsius', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_yield_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
            ],
        ),
    ]
