# Generated by Django 5.2.4 on 2026-03-14 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productionbatch',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.productionprocess'),
        ),
        migrations.AddField(
            model_name='processoutput',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expected_outputs', to='production.productionprocess'),
        ),
        migrations.AddField(
            model_name='processinput',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expected_inputs', to='production.productionprocess'),
        ),
        migrations.AddField(
            model_name='processchemical',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chemicals', to='production.productionprocess'),
        ),
        migrations.AddField(
            model_name='productionprocess',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='production.productionstage'),
        ),
    ]
