# Generated by Django 5.2.4 on 2026-03-12 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_item_current_stock_item_track_by_lot_and_more'),
        ('production', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchchemicalusage',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.item'),
        ),
        migrations.AddField(
            model_name='batchinput',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='batchchemicalusage',
            name='stock_lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.stocklot'),
        ),
        migrations.AlterField(
            model_name='batchinput',
            name='hide_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batchinput',
            name='stock_lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.stocklot'),
        ),
    ]
