# Generated by Django 5.2.4 on 2026-03-15 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processchemical',
            options={'ordering': ['sequence_order']},
        ),
        migrations.AlterModelOptions(
            name='productionbatch',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='productionstage',
            options={'ordering': ['sequence_order']},
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='productionprocess',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productionbatch',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('QA_HOLD', 'QA Hold'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='productionprocess',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
