# Generated by Django 5.2.12 on 2026-03-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_alter_processchemical_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionbatch',
            name='base_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Base weight for calculating chemical recipes', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='quantity_hides',
            field=models.PositiveIntegerField(blank=True, help_text='Number of hides/skins processed', null=True),
        ),
    ]
