# Generated by Django 5.2.12 on 2026-03-20 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_location_item_current_unit_price_item_reorder_point_and_more'),
        ('production', '0004_productionbatch_base_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processchemical',
            name='instruction',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='processchemical',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='processchemical',
            name='quantity_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
